Imports DevExpress.XtraPivotGrid
Imports System
Imports System.Collections.Generic

Namespace XtraPivotGrid_CreateDrillDownDataSourceAsync
	Partial Public Class Form1
		Inherits DevExpress.XtraEditors.XtraForm

		Private dForm As DrillDownForm
		Public Sub New()
			InitializeComponent()
			AddHandler Me.Load, AddressOf Form1_Load
			AddHandler pivotGridControl1.CellClick, AddressOf pivotGridControl1_CellClick
			' This line of code is generated by Data Source Configuration Wizard
			linqServerModeSource1.QueryableSource = (New XtraPivotGrid_CreateDrillDownDataSourceAsync.DataClasses1DataContext()).Invoices
		End Sub
		Async Sub pivotGridControl1_CellClick(ByVal sender As Object, ByVal e As DevExpress.XtraPivotGrid.PivotCellEventArgs)
			Dim pivot As PivotGridControl = TryCast(sender, PivotGridControl)
			If dForm.IsDisposed Then
				LoadDrillDownForm()
			End If

			'Check whether an asynchronous operation is in progress.
			If Not pivot.IsAsyncInProgress Then

				' Get the record set associated with the clicked cell.
				dForm.DataSource = Await pivot.CreateDrillDownDataSourceAsync(e.ColumnIndex, e.RowIndex, 25, New List(Of String) From {"ProductName", "Quantity"})
			End If
		End Sub
		Sub Form1_Load(ByVal sender As Object, ByVal e As EventArgs)
			LoadDrillDownForm()
		End Sub
		Sub LoadDrillDownForm()
			dForm = New DrillDownForm()
			dForm.Show()
		End Sub
	End Class
End Namespace